version: '2'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - $NEXTCLOUD_PATH/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ${NEXTCLOUD_PATH}/data-html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITEPROTOCOL=https

  collabora:
    image: 'collabora/code'
    restart: always
    container_name: collabora
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    environment:
      - domain=${NEXTCLOUD_TRUSTED_DOMAINS}
      - dictionaries='fr en es'
      - VIRTUAL_HOST=${COLLAB_DOMAIN}
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https